### ISSUE TITLE
Learner Information - Program Status - Once practitioners chooses "Closed" for program status, the learner becomes an "exited" learner and their account is no longer accessible until they register again.

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/Learninghub#188]

**Comment by tgascoigne14** [comment]
This was working before. I closed sttigascoigne0 and even changed the username to the client ID. I wasn't able to sign in again (which is correct), but I was not able to register again (it said I had an active account)

**Comment by hemantcci** [comment]
I have changed it back.
