### ISSUE TITLE
Roles - If a user is assigned the SIN manager role, they should have full access to the learner database. 

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/Learninghub#253]
Some of the managers will not have another role. I assigned the stlhadmin to just the SIN manager and don't have access to the learner database. This data will most likely be collected before the learner is assigned a practitioner (not sure if this needs to be known)

**Comment by ccmorris** [comment]
Does the "LHUB admin" role give the required permissions? That role should give edit permissions on every learner, and that permission is a prerequisite to view/edit SIN numbers.

**Comment by tgascoigne14** [comment]
Ok - leave this with me. I think it works great and will be fine as is. I will let you know
