### ISSUE TITLE
Registration Form - Training - Update “Were you referred by Employment Ontario Self Service (EOSS)?"

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/Learninghub#256]
to 

Were you referred by Request a Service Provider (RASP)?

**Comment by ccmorris** [comment]
There is help text for this field:

> The Employment Ontario Self Service (EOSS) tool is located on the Ministry of Advanced Education and Skills Development's Employment Ontario website: http://www.tcu.gov.on.ca/eng/employmentontario/

Should I just remove that help text?

**Comment by tgascoigne14** [comment]
Yes please
