### ISSUE TITLE
Add Course Button - Allowing for users to press the submit more than one time causing duplicate course registrations

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/Learninghub#266]

**Comment by ccmorris** [comment]
I pressed the Add Course button many times and was only registered for the course once. Can you try this one with a learner account Tina?

**Comment by ccmorris** [comment]
note to self: it is allowing you to submit the form many times, and sends the practitioner/admin email multiple times, and the user ends up only registered once.

**Comment by ccmorris** [comment]
fixed! 😊
