### ISSUE TITLE
Change “aboriginal” to “indigenous” on entire registration:

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/Learninghub#271]
Referred In (linked to registration form) - Currently Aboriginal Services

Referred Out - portal only - Currently Aboriginal Services

What Language Do You Speak At Home? (linked to registration form) - Currently Aboriginal

What Language Was Spoken At Last Workplace? (linked to registration form) - Currently Aboriginal

**Comment by ccmorris** [comment]
I did not find Aboriginal Services in Referral Out in the portal. I changed the other three

**Comment by ccmorris** [comment]
Nevermind, I found it in this field: Other Programs/Services Referral Out
It was called Services for Aboriginal People. I changed it to Services for Indigenous People
