### ISSUE TITLE
Reorder the status section and add a new question -  We would like to add a new question “Country of Birth”

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/Learninghub#272]
![pasted image 0 (5)](https://user-images.githubusercontent.com/8631079/82918676-0e507300-9f43-11ea-8b50-610320108bd0.png)

**Comment by ccmorris** [comment]
Country of Birth field: textfield or dropdown? Dropdown options if applicable?

**Comment by tgascoigne14** [comment]
textfield please!

**Comment by ccmorris** [comment]
They left a gap in the second row in the diagram, I suspect it is for the "Please specify" field when the Status in Canada is "Other". That's just not going to work. I get that it just, fits in there, but it doesn't make sense for the logical order of the fields. The "Please specify" field comes immediately after the Status in Canada, obviously. But then if it is in that blank spot then if you follow the order of fields in the whole form, then it is the third field after. I hope that makes sense, it's hard to explain.

**Comment by ccmorris** [comment]
If you think about the tab order of the fields then that kinda visualizes how messed up it is
