### ISSUE TITLE
(In the portal only) Can you move the “Number of Dependants” down to the left of “What is your income source?”

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/Learninghub#273]
![pasted image 0 (6)](https://user-images.githubusercontent.com/8631079/82918801-37710380-9f43-11ea-895b-e2de9645cd32.png)

**Comment by ccmorris** [comment]
to the left? the screenshot points to the right

**Comment by tgascoigne14** [comment]
Lol you're right. They requested to the left so I assume that arrow is just trying to show us what section they want us to move the question to.
