### ISSUE TITLE
Portal Export - Please Specify file attached to the Status in Canada question: Please add Please Specify field attached to the Status in Canada question to the portal export file.

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/Learninghub#276]
I copied and pasted this request - let me know if it doesn't make sense.

**Comment by ccmorris** [comment]
"file" should read "field", but yes it makes sense to me. There are actually 2 different exports, one for practitioners and a separate export for LHUB admins. I added this field to both, since they both had the "Status in Canada" field already.
