### ISSUE TITLE
SIN collection - Disable one question for now: "I will call LHUB and give my sin"

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/Learninghub#282]
![LH Edit](https://user-images.githubusercontent.com/8631079/88212192-db65eb00-cc24-11ea-9b8d-d647723000d3.png)

**Comment by tgascoigne14** [comment]
This question is still on the form - can you please hide it for now?

**Comment by ccmorris** [comment]
It turns out there was an error message when I press save for this change. I didn't notice it last time. It does not allow removing an option that is already used.

Can I replace this option with another one in the existing registration data?

**Comment by tgascoigne14** [comment]
I'm sure that's not a problem. Do you have a suggestion?

**Comment by ccmorris** [comment]
My suggestion is that "I Will Call..." is replaced with "Call me..." for the existing registrations.

**Comment by tgascoigne14** [comment]
Okay, let's try it.

**Comment by ccmorris** [comment]
Now that I think about it, this field does not exist (yet) on the live site, so it is just testing data that will be affected. It's fine.

This is done.
