### ISSUE TITLE
Learner Portal - Start Learning Block and the Learner Login Block lead to unauthorized pages.

### ISSUE THREAD

**Issue by alyssaphillion** [CCI-Studios/Learninghub#98]
When logged in as a user, you can click on the three coloured blocks from the homepage or other inner pages. They lead to a client summary as well as a personal information list, which shouldn't be accessible to a learner.

**Comment by tgascoigne14** [comment]
This is happening when logged into all portal i.e. practitioner and admin.

**Comment by hemantcci** [comment]
I have disabled the blocks when logged in. Because they go to login or registration when you are logged in It doesn't make sense for drupal.
